# Generated by Django 2.2.3 on 2019-08-10 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('votes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('in progress', 'in progress'), ('completed', 'completed')], default='waiting', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'critical'), ('important', 'important'), ('medium', 'medium')], default='medium', max_length=20)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.BlogPost')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f_rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(blank=True, null=True)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.BlogPost')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f_poster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
