# Generated by Django 2.2.4 on 2019-08-15 05:11

from django.db import migrations, models
import helpdesk.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_auto_20190814_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, null=True, storage=helpdesk.storage_backends.MediaStorage(), upload_to='media'),
        ),
    ]
